version: "3.8"

services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=coinpanel
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    ports:
      - 5432:5432
    command: postgres -c shared_preload_libraries=pg_stat_statements
    # Use this to not lose the data after a run
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    # Use this to lose the data after a run
    # volumes:
    #   - ./sql:/docker-entrypoint-initdb.d
    # tmpfs:
    #   - /var/lib/postgresql/data:rw,noexec,nosuid,size=500m
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=coinpanel --username=dbuser --host=localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ingestion:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - BINANCE_WS_URI=wss://stream.binance.com:9443/ws
      - PSQL_CONN=postgresql://dbuser:dbpass@postgres:5432/coinpanel
    command: python3 src/ingestion.py
    healthcheck:
      test: [ "CMD-SHELL", "test -f /home/app/ready.txt" ]
      interval: 5s
      timeout: 5s
      retries: 5

  webserver:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ingestion:
        condition: service_healthy
    command: uvicorn main:app --app-dir src --reload --host 0.0.0.0
    environment:
      - PSQL_CONN=postgresql://dbuser:dbpass@postgres:5432/coinpanel

#---To test, run only `postgres` and `testing` services---#
  testing:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - BINANCE_WS_URI=wss://stream.binance.com:9443/ws
      - PSQL_CONN=postgresql://dbuser:dbpass@postgres:5432/coinpanel
      - TEST_DB_CONN=postgresql://dbuser:dbpass@postgres:5432/test_coinpanel
    command: pytest src/tests/tests.py
